spring.application.name=ai-recruitment-management
spring.datasource.url=jdbc:mysql://localhost:3306/ai_recruitment_managaement_db
spring.datasource.username=root
spring.datasource.password=Jyoti@88

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true